from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('uploadvVal', views.uploadvVal, name='uploadvVal'),
    path('uploadvtest', views.uploadvtest, name='uploadvtest'),
    path('', views.home, name='home'),
    path('csv_simple_write', views.csv_simple_write, name='csv_simple_write'),
    path('about', views.index, name='HomePage'),
    path('contact', views.index, name='HomePage'),
    path('shortlist', views.shortlist, name='shortlist'),
    path('shortlists', views.shortlists, name='shortlists'),
    path('company', views.company, name='company'),
    path('login', views.login, name='login'),
    path('jobs', views.index, name='HomePage'),
    path('cvacancyTestData', views.cvacancyTestData, name='cvacancyTestData'),
    path('delete', views.delete, name='DeletePage'),
    path('cvapplicants/<int:id>/', views.cvapplicants, name='cvapplicants'),
    path('vdelete/<int:id>/', views.Vdelete, name='DeleteVacancy'),
    path('cvdelete/<int:id>/', views.cvdelete, name='DeleteCompanyVacancy'),
    path('cdelete/<int:id>/', views.cdelete, name='Deletecomp'),
    path('cactivate/<int:id>/', views.cactivate, name='cactivate'),
    path('udelete/<int:id>/', views.udelete, name='Deletecandidate'),
    path('testdata/<int:id>/', views.testdata, name='testdata'),
    path('check_login', views.check_login, name='DeletePage'),
    path('comp_register', views.comp_register, name='DeletePage'),
    path('admin', views.admin_login, name='AdminLogin'),
    path('admin_dash', views.admin_dash, name='AdminDash'),
    path('admin_check_login', views.admin_check_login, name='adminchecklogin'),
    path('complist', views.companies, name='companies'),
    path('candlist', views.candidates, name='candidates'),
  
    path('results', views.results, name='results'),
    path('vacancies', views.vacancies, name='vacancies'),
    path('cvacancies', views.compvacancies, name='cvacancies'),
    path('questions', views.questions, name='questions'),
    path('capplicants', views.capplicants, name='capplicants'),
    path('cactivate/<int:id>/', views.cactivate, name='cactivate'),
    path('cdashboard', views.cdashboard, name='cdashboard'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('comp_login', views.comp_login, name='comp_login'),
    path('comp_check_login', views.comp_check_login, name='comp_check_login'),
    path('check', views.check, name='check'),
    path('cdashboard', views.cdashboard, name='cdashboard'),
	path('register', views.register, name='register'),
	path('save', views.save, name='save'),
	path('check', views.check, name='Check'),
	path('vacancy', views.vacancy, name='Vacancy'),
    path('qualifications', views.qualifications, name='qualifications'),
    path('addQualification', views.addQualification, name='addQualification'),
	path('addVacancy', views.addVacancy, name='AddVacancy'),
    path('addExperience', views.addExperience, name='addExperience'),
    path('saveExperience', views.saveExperience, name='saveExperience'),
    path('saveQualification', views.saveQualification, name='saveQualification'),
    path('cvapply/<int:id>/', views.cvapply, name='cvapply'),
    
    path('cvsave', views.cvsave, name='cvsave'),
    path('upload', views.upload, name='upload'),
    path('logout', views.logout, name='logout'),
    path('complogout', views.complogout, name='complogout'),
    path('admlogout', views.admlogout, name='admlogout'),
    path('details/<int:id>', views.details, name='details'),
    path('exp/<int:id>', views.exp, name='exp'),
    path('capplicants/<int:id>/', views.capplicants, name='capplicants'),
    path('vtestdata/<int:id>/', views.vtestdata, name='vtestdata'),

]
